//! Build script for `garraia-auth` (GAR-391b).
//!
//! Generates a `DUMMY_HASH` constant containing an Argon2id PHC string over a
//! discarded random secret. Used by the constant-time anti-enumeration path
//! in `verify_credential`: when the user is not found (or the account is not
//! active), we still verify the supplied password against this dummy hash so
//! the wall-clock latency of "user not found" matches the latency of "user
//! exists, wrong password". Without this, an attacker can enumerate valid
//! emails just by timing the response.
//!
//! The hash is generated at COMPILE time (not at startup) because:
//!   1. Argon2id with `m=64MiB, t=3, p=4` costs ~200ms on a 2GB CI runner.
//!      Doing it once at compile time avoids paying that on every binary boot.
//!   2. The dummy secret never leaves this build script — only the PHC string
//!      embeds in the binary, and PHC is one-way.
//!
//! Output: `$OUT_DIR/dummy_hash.rs` containing `pub const DUMMY_HASH: &str = "...";`
//! which `src/hashing.rs` includes via `include!(concat!(env!("OUT_DIR"), "/dummy_hash.rs"));`.

use std::env;
use std::fs;
use std::path::PathBuf;

use argon2::{Algorithm, Argon2, Params, Version};
use password_hash::rand_core::{OsRng, RngCore};
use password_hash::{PasswordHasher, SaltString};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    // RFC 9106 first recommendation: m=65536 KiB (64 MiB), t=3, p=4, output=32B.
    let params = Params::new(64 * 1024, 3, 4, Some(32))
        .expect("Argon2id params per RFC 9106 first recommendation must be valid");
    let argon2 = Argon2::new(Algorithm::Argon2id, Version::V0x13, params);

    // Generate a random 32-byte secret. We hash it and immediately drop it —
    // the only thing that survives is the PHC string. The secret has no
    // meaning; we never need to verify against it. We just need a stable
    // PHC string that has the same cost profile as a real password hash.
    //
    // `OsRng` is pulled from `password_hash::rand_core` (rand_core 0.6) to
    // avoid a multi-version conflict with `rand 0.9` / `rand_core 0.9`.
    let mut rng = OsRng;
    let mut secret_bytes = [0u8; 32];
    rng.fill_bytes(&mut secret_bytes);
    let salt = SaltString::generate(&mut OsRng);

    let phc = argon2
        .hash_password(&secret_bytes, &salt)
        .expect("Argon2id hash of 32 random bytes with valid params cannot fail");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("cargo always sets OUT_DIR"));
    let dest = out_dir.join("dummy_hash.rs");
    let content = format!(
        "/// Argon2id PHC string over a discarded random secret. Generated by build.rs.\n\
         /// See garraia-auth `hashing.rs` for the constant-time anti-enumeration path.\n\
         pub const DUMMY_HASH: &str = \"{}\";\n",
        phc
    );
    fs::write(&dest, content).expect("write dummy_hash.rs to OUT_DIR");
}
