#!/usr/bin/env python3
"""Hard coverage floor for the `coverage` job of ci.yml (#1566, criterio 2).

Reads the `lcov.info` produced by `cargo llvm-cov` and fails the build when
total line coverage falls below a floor.

Why this exists: until #1566 the `coverage` job was pure observability — it
measured, posted a PR comment and moved on, so nothing stopped coverage from
sliding. A gate without a threshold is a report, not a control.

Why it parses `lcov.info` and not `coverage-summary.txt`: the number this gate
enforces has to be *the same number* that `scripts/quality/freeze-baseline.py`
writes into `.quality/baseline.json`. Both go through
`scripts/quality/parse-llvm-cov.py`, loaded here by path, so the gate and the
baseline cannot drift apart by having two parsers. The textual summary is a
different rendering (per-region/per-function columns) and would invite exactly
that drift.

Fail-closed: a missing or empty `lcov.info` is a FAILURE here, not a skip. In
the ci.yml job the file is generated by the immediately preceding step, so its
absence means the instrumented run broke — and "coverage could not be measured"
must never read as "coverage is fine". This is the opposite of the ratchet's
best-effort posture (plan 0064), where the artifact legitimately may not exist
yet; see `.github/workflows/quality-ratchet.yml`.

This gate is NOT the AI Quality Ratchet. `compare.py` stays `--mode
report-only` and its promotion to blocking is still plan 0064 PR-4, pending
explicit approval. The two are independent: this one enforces a single
published number from the ROADMAP.

Usage:
    python3 scripts/ci/coverage_gate.py lcov.info --floor 70.0

Exit codes:
    0 — coverage >= floor
    1 — coverage < floor, or coverage not measurable (fail-closed)
    2 — bad invocation
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

# scripts/ci/coverage_gate.py → scripts/quality/parse-llvm-cov.py
PARSER_PATH = Path(__file__).resolve().parents[1] / "quality" / "parse-llvm-cov.py"


def _load_parser(path: Path = PARSER_PATH):
    """Load the hyphenated parse-llvm-cov.py as a module (same trick its tests use)."""
    spec = importlib.util.spec_from_file_location("parse_llvm_cov", path)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise RuntimeError(f"cannot load coverage parser at {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def evaluate(lcov_path: Path, floor_pct: float, parser=None) -> tuple[int, str]:
    """Return (exit_code, human message). Pure: no printing, no sys.exit."""
    mod = parser if parser is not None else _load_parser()
    summary = mod.parse_lcov(lcov_path)

    pct = summary.get("coverage_pct")
    if summary.get("status") != "present" or pct is None:
        return (
            1,
            f"FAIL: coverage not measurable from {lcov_path} "
            f"(status={summary.get('status')!r}). Fail-closed: an unmeasured "
            f"run is not a passing run.",
        )

    lines_hit = summary.get("lines_hit", 0)
    lines_total = summary.get("lines_total", 0)
    detail = f"{pct:.2f}% ({lines_hit}/{lines_total} lines, {summary.get('files', 0)} files)"

    if pct < floor_pct:
        return (
            1,
            f"FAIL: coverage {detail} is below the floor of {floor_pct:.2f}%. "
            f"Add tests for the code this PR touches, or change the floor "
            f"deliberately in ci.yml and in the ROADMAP together.",
        )

    return (0, f"OK: coverage {detail} meets the floor of {floor_pct:.2f}%.")


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Fail the build below a coverage floor.")
    ap.add_argument("lcov", type=Path, help="path to lcov.info from cargo llvm-cov")
    ap.add_argument(
        "--floor",
        type=float,
        required=True,
        help="minimum total line coverage percentage (inclusive)",
    )
    args = ap.parse_args(argv[1:])

    if not (0.0 <= args.floor <= 100.0):
        print(f"usage error: --floor must be in [0, 100], got {args.floor}", file=sys.stderr)
        return 2

    code, message = evaluate(args.lcov, args.floor)
    print(message, file=sys.stderr if code else sys.stdout)
    return code


if __name__ == "__main__":
    sys.exit(main(sys.argv))
