#!/usr/bin/env bash
# gen-auth-secrets.sh — print a ready-to-paste env block for GarraIA auth.
#
# Prints to STDOUT ONLY — it never writes a file (secrets are env-only:
# CLAUDE.md rule #1, docs/auth-config.md §7). Redirect the output yourself
# if you want it persisted, e.g.:
#   sudo sh -c './scripts/gen-auth-secrets.sh > /etc/garraia/env \
#     && chown root:garraia /etc/garraia/env && chmod 640 /etc/garraia/env'
#
# Postgres endpoint defaults can be overridden via env:
#   GARRAIA_PG_HOST (127.0.0.1) / GARRAIA_PG_PORT (5432) / GARRAIA_PG_DB (garraia_workspace)
set -euo pipefail

if ! command -v openssl >/dev/null 2>&1; then
  echo "error: openssl not found in PATH" >&2
  exit 1
fi

jwt=$(openssl rand -hex 32)
refresh=$(openssl rand -hex 32)
upload=$(openssl rand -hex 32)
vault=$(openssl rand -hex 32)
login_pw=$(openssl rand -hex 24)
signup_pw=$(openssl rand -hex 24)
app_pw=$(openssl rand -hex 24)

# Every value must be pairwise distinct (docs/auth-config.md §3.3 for
# jwt/refresh; same policy for the role passwords). Collision at these
# entropy sizes is theoretical — the check exists for policy audit, so
# failing closed beats retry loops. The message never echoes a value.
dups=$(printf '%s\n' "$jwt" "$refresh" "$upload" "$vault" \
  "$login_pw" "$signup_pw" "$app_pw" | sort | uniq -d)
if [ -n "$dups" ]; then
  echo "error: generated values collided; run the script again" >&2
  exit 1
fi

pg_host="${GARRAIA_PG_HOST:-127.0.0.1}"
pg_port="${GARRAIA_PG_PORT:-5432}"
pg_db="${GARRAIA_PG_DB:-garraia_workspace}"

cat <<EOF
# ── GarraIA auth env block — generated by scripts/gen-auth-secrets.sh ──
# Paste into /etc/garraia/env (chmod 640) or export in your shell.
# NEVER commit this output. Full runbook: docs/auth-config.md §7.
GARRAIA_JWT_SECRET=$jwt
GARRAIA_REFRESH_HMAC_SECRET=$refresh
GARRAIA_UPLOAD_HMAC_SECRET=$upload
GARRAIA_VAULT_PASSPHRASE=$vault
GARRAIA_LOGIN_DATABASE_URL=postgres://garraia_login:$login_pw@$pg_host:$pg_port/$pg_db
GARRAIA_SIGNUP_DATABASE_URL=postgres://garraia_signup:$signup_pw@$pg_host:$pg_port/$pg_db
GARRAIA_APP_DATABASE_URL=postgres://garraia_app:$app_pw@$pg_host:$pg_port/$pg_db

# ── Run against Postgres as superuser AFTER the workspace migrations ──
# (migrations 007/008/010 create these roles NOLOGIN; docs/auth-config.md §7.4)
# ALTER ROLE garraia_login  WITH LOGIN PASSWORD '$login_pw';
# ALTER ROLE garraia_signup WITH LOGIN PASSWORD '$signup_pw';
# ALTER ROLE garraia_app    WITH LOGIN PASSWORD '$app_pw';
EOF
